# Generated by Django 5.1.2 on 2024-12-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
