# Generated by Django 5.1.4 on 2025-01-21 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must start with '07' or '01' and be exactly 10 digits.", regex='^(07|01)\\d{8}$'), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
