# Generated by Django 5.1.2 on 2024-12-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_newsarticle_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='epapers/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
