# Generated by Django 5.1.4 on 2025-01-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalimage',
            name='placeholder',
            field=models.CharField(default='placeholder_1', max_length=100),
        ),
    ]
