# Generated by Django 5.1.2 on 2024-12-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_epaper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epaper',
            old_name='date_uploaded',
            new_name='date_posted',
        ),
        migrations.AlterField(
            model_name='epaper',
            name='pdf_file',
            field=models.FileField(upload_to='epapers/', verbose_name='ePaper PDF'),
        ),
    ]
