# Generated by Django 5.1.2 on 2024-12-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_date_uploaded_epaper_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epaper',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='epapers/thumbnails/'),
        ),
    ]
