# Generated by Django 5.1.2 on 2024-12-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_epaper_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epaper',
            name='thumbnail',
        ),
    ]
