# Generated by Django 5.1.2 on 2024-12-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_epaper_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epaper',
            old_name='date_posted',
            new_name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='epaper',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='epaper',
            name='pdf',
            field=models.FileField(default='epapers/News_Wire.pdf', upload_to='epapers/'),
        ),
    ]
